[package]
name = "NetworkTests"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
local-ip-address = "0.6"
pin-project = "1.1.10"
atomic-wait = "1"
